// Generated by CoffeeScript 1.6.3
/**
@author Andrey Linko <su2ny@mail.ru>
@class Krypton.core.view.region.north.Panel

North region. Header panel.
*/

Ext.define('Schedule.view.region.detail.Panel', {
  extend: 'Ext.container.Container',
  region: 'east',
  baseCls: 'x-detail',
  width: 305,
  border: "0 0 0 1",
  initComponent: function() {
    return this.callParent(arguments);
  }
});
