// Generated by CoffeeScript 1.6.3
/**
@author Andrey Linko <su2ny@mail.ru>
@class Krypton.core.view.Viewport

Viewport. Render application.
Has five regions: header, tools, center, control, workspace
*/

Ext.define('Schedule.view.Viewport', {
  extend: 'Ext.container.Viewport',
  inject: ['header', 'navigation', 'workspace', 'detail'],
  layout: 'border',
  initComponent: function() {
    Ext.state.Manager.setProvider(Ext.create('Ext.state.LocalStorageProvider'));
    this.items = [this.header, this.navigation, this.workspace, this.detail];
    return this.callParent(arguments);
  }
});
