// Generated by CoffeeScript 1.6.3
var app, coffeescript, express, http, jade, path;

coffeescript = require("connect-coffee-script");

express = require("express");

jade = require("jade-static");

http = require("http");

path = require("path");

app = express();

app.configure(function() {
  var directory;
  app.set("port", process.env.PORT || 3000);
  if (process.env.NODE_ENV === "production") {
    directory = path.join(__dirname, "build/krypton/production");
  } else {
    directory = path.join(__dirname);
  }
  app.use(express.bodyParser());
  app.use(jade(directory));
  app.use(coffeescript(directory));
  return app.use(express["static"](directory));
});

http.createServer(app).listen(app.get("port"), function() {
  return console.log("Express server listening on port " + (app.get("port")));
});
