// Generated by CoffeeScript 1.6.3
/**
@author Andrey Linko <su2ny@mail.ru>
@class Krypton.core.view.region.north.Panel

North region. Header panel.
*/

Ext.define('Schedule.view.region.workspace.Panel', {
  extend: 'Ext.panel.Panel',
  inject: ['filters', 'list'],
  layout: 'border',
  region: 'center',
  border: false,
  initComponent: function() {
    this.items = [this.filters, this.list];
    return this.callParent(arguments);
  }
});
